# Main Traefik Configuration for Dokploy
# Copy to: /etc/dokploy/traefik/traefik.yml

global:
  sendAnonymousUsage: false

api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
  traefik:
    address: ":8080"

providers:
  docker:
    exposedByDefault: false
    watch: true
    network: dokploy-network
    endpoint: unix:///var/run/docker.sock
  file:
    directory: /etc/dokploy/traefik/dynamic
    watch: true

log:
  level: INFO
  format: json

accessLog:
  format: json