# Additional Traefik routes for Demo and Seller interfaces
# Add this to your existing /etc/dokploy/traefik/dynamic/dokploy.yml

http:
  routers:
    # Demo Interface - Viewer Platform with LiveKit Client
    demo-frontend-router:
      rule: Host(`demo.blytz.app`)
      service: demo-frontend-service
      entryPoints:
        - web
      middlewares:
        - redirect-to-https

    demo-frontend-router-secure:
      rule: Host(`demo.blytz.app`)
      service: demo-frontend-service
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt

    # Seller Interface - Broadcaster Platform with LiveKit SDK
    seller-frontend-router:
      rule: Host(`seller.blytz.app`)
      service: seller-frontend-service
      entryPoints:
        - web
      middlewares:
        - redirect-to-https

    seller-frontend-router-secure:
      rule: Host(`seller.blytz.app`)
      service: seller-frontend-service
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt

    # LiveKit Server for WebRTC streaming
    livekit-router:
      rule: Host(`livekit.blytz.app`)
      service: livekit-service
      entryPoints:
        - web
      middlewares:
        - redirect-to-https

    livekit-router-secure:
      rule: Host(`livekit.blytz.app`)
      service: livekit-service
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt

  services:
    # Demo Frontend Service
    demo-frontend-service:
      loadBalancer:
        servers:
          - url: http://blytz-demo-prod:3001
        passHostHeader: true

    # Seller Frontend Service
    seller-frontend-service:
      loadBalancer:
        servers:
          - url: http://blytz-seller-prod:3002
        passHostHeader: true

    # LiveKit Service
    livekit-service:
      loadBalancer:
        servers:
          - url: http://blytz-livekit-prod:7880
        passHostHeader: true