global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'auction-service'
    static_configs:
      - targets: ['auction:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'payment-service'
    static_configs:
      - targets: ['payment:8082']
    metrics_path: '/metrics'
    scrape_interval: 10s