openapi: 3.1.0
info:
  title: Blytz Chat Service
  version: 1.0.0
paths:
  /chat/send:
    post:
      summary: Send chat message
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                streamId: { type: string }
                userId: { type: string }
                message: { type: string }
      responses:
        "200": { description: Message broadcasted }

  /chat/stream/{streamId}:
    get:
      summary: Stream chat feed (SSE or WebSocket)
      parameters:
        - name: streamId
          in: path
          required: true
          schema: { type: string }
      responses:
        "200": { description: Live chat stream }
