openapi: 3.1.0
info:
  title: Blytz Payment Service
  version: 1.0.0
paths:
  /payment/intent:
    post:
      summary: Create payment intent
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                orderId: { type: string }
                amount: { type: number }
                method: { type: string }
      responses:
        "200": { description: Payment intent created }

  /payment/webhook:
    post:
      summary: Handle payment gateway webhook
      requestBody:
        content:
          application/json:
            schema: { type: object }
      responses:
        "200": { description: Payment event received }
