include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore
    # Suppress noisy warnings that don't affect functionality
    public_member_api_docs: ignore
    lines_longer_than_80_chars: ignore
    eol_at_end_of_file: ignore
    sort_pub_dependencies: ignore
    directives_ordering: ignore

linter:
  rules:
    prefer_single_quotes: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true